#!/bin/bash
# Copyright: Isaac David Orozco Delgado (c) 2024
# GNU General Public License v3.0+ (see LICENSE or https://www.gnu.org/licenses/gpl-3.0.txt)
# SPDX-License-Identifier: GPL-3.0-or-later

cmdChk() {
	if ! type "$1" > /dev/null 2>&1; then
		echo -e "\e[0;31mERROR: \e[1;37m$1 not found,\e[0;31m Aborting...\e[0m"
		exit 2
	fi
}

NAME="Make Wah-Package"
cmdChk dirname

if [ -f "${WAHROOT}/usr/lib/makewpkg/core.wah" ]; then
	CORE="${WAHROOT}/usr/lib/makewpkg"
else
	if [ -f "${HOME}/.local/usr/lib/makewpkg/core.wah" ]; then
		CORE="${HOME}/.local/usr/lib/makewpkg"
	else
		if [ -f "$(dirname $0)/funcs/core.wah" ]; then
			CORE="$(dirname $0)/funcs"
			echo "WARN: Working on local directory core mode."
		else
			echo "ERROR: $NAME core script not found"
			exit 1
		fi
	fi
fi
source "${CORE}/core.wah"

if [ -f "${WAHROOT}/usr/lib/makewpkg/wahmain.wah" ]; then
	SRC="${WAHROOT}/usr/lib/makewpkg"
else
	if [ -f "${HOME}/.local/usr/lib/makewpkg/wahmain.wah" ]; then
		SRC="${HOME}/.local/usr/lib/makewpkg"
	else
		if [ -f "$(dirname $0)/funcs/wahmain.wah" ]; then
			SRC="$(dirname $0)/funcs"
			WARN "Working on local directory main mode."
		else
			ERROR "$NAME main script not found" 1
		fi
	fi
fi
source "${SRC}/wahmain.wah"
