.TH WPM 8 "30 August 2024" "version Alpha 1.0.0" "Wah Package-Manager"

.SH NAME
wpm \- Wah Package-Manager

.SH SYNOPSIS
.B wpm
[\fIOPTION\fR] [\fIARGUMENT\fR]

.SH DESCRIPTION
.B wpm
is a simple package manager for Panwah.

.SH OPTIONS
.TP
.B \-h, \-\-help
Display a help message and exit.

.TP
.B \-v, \-\-version
Show the version of the program and exit.

.SH AUTHOR
Isaac David Orozco Delgado (Reisy RedPanda) <opensrcrdp@gmail.com>
